version: '3'

services:
  gem5_sim:
    image: gem5_dramsim3
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - GEM5_VERSION=v24.0.0.1
        - BUILD_ISA=X86
    container_name: gem5_sim_container
    volumes:
      - ./work:/work
    tty: true
    stdin_open: true


